# Generated by Django 5.2.6 on 2025-10-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cupos', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Activa', max_length=15)),
            ],
            options={
                'db_table': 'actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InscripcionActividad',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inscripcion_actividad',
                'managed': False,
            },
        ),
    ]
