# Generated by Django 5.2.6 on 2025-10-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('espacio', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moneda', models.CharField(blank=True, max_length=3, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_reserva', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
    ]
