# Generated by Django 5.2.6 on 2025-10-17 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioComunal',
            fields=[
                ('id_espacio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto_hora', models.IntegerField(default=0)),
                ('imagen', models.ImageField(upload_to='espacios/')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'espacio_comunal',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Cancelada', 'Cancelada')], default='Activa', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('id_espacio', models.ForeignKey(db_column='id_espacio', on_delete=django.db.models.deletion.CASCADE, to='Reserva.espaciocomunal')),
                ('id_vecino', models.ForeignKey(db_column='id_vecino', on_delete=django.db.models.deletion.CASCADE, to='Usuarios.vecino')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
    ]
