# Generated by Django 5.2.6 on 2025-11-15 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
                ('orden_compra', models.CharField(max_length=50)),
                ('monto', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('id_vecino', models.ForeignKey(db_column='id_vecino', null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.vecino')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transaccion',
            },
        ),
    ]
