# Generated by Django 5.2.6 on 2025-10-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vecino',
            fields=[
                ('id_vecino', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=15)),
                ('foto', models.ImageField(blank=True, default='perfiles/default.png', null=True, upload_to='perfiles/')),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='evidencias_vecinos/')),
            ],
            options={
                'db_table': 'vecino',
                'managed': False,
            },
        ),
    ]
