# Generated by Django 5.2.6 on 2025-10-08 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vecino',
            options={},
        ),
    ]
