# Generated by Django 5.2.6 on 2025-10-08 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_vecino_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vecino',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Usuarios.rol'),
            preserve_default=False,
        ),
    ]
