# Generated by Django 5.2.6 on 2025-10-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id_certificado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_emision', models.DateTimeField(blank=True, null=True)),
                ('folio', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('firma_digital', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'certificado',
                'managed': False,
            },
        ),
    ]
