# Generated by Django 5.2.6 on 2025-10-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('documento_adj', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_postulacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'proyecto',
                'managed': False,
            },
        ),
    ]
