# Generated by Django 5.2.6 on 2025-11-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoProyecto',
            fields=[
                ('id_voto', models.AutoField(primary_key=True, serialize=False)),
                ('voto', models.BooleanField()),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'voto_proyecto',
                'managed': False,
            },
        ),
    ]
