# Generated by Django 5.2.6 on 2025-10-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name': 'Proyecto vecinal', 'verbose_name_plural': 'Proyectos vecinales'},
        ),
    ]
