# Generated by Django 5.2.6 on 2025-11-15 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Solicitud Ciudadana', 'verbose_name_plural': 'Solicitudes Ciudadanas'},
        ),
    ]
