# Generated by Django 5.2.6 on 2025-10-23 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('global', 'Global (todos)'), ('directorio', 'Solo Directorio')], default='global', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_vecino', models.IntegerField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_estado', models.DateTimeField(auto_now=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='Notificaciones.notificacion')),
            ],
            options={
                'unique_together': {('notificacion', 'id_vecino')},
            },
        ),
    ]
